* 데이터 로드 및 전처리
* 모델 정의
* 학습
* 문장 생성

## 데이터 로드 및 전처리

In [ ]:
text = '''
동해 물과 백두산이 마르고 닳도록
하느님이 보우하사 우리나라 만세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
남산 위에 저 소나무, 철갑을 두른 듯
바람 서리 불변함은 우리 기상일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
가을 하늘 공활한데 높고 구름 없이
밝은 달은 우리 가슴 일편단심일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
이 기상과 이 맘으로 충성을 다하여
괴로우나 즐거우나 나라 사랑하세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
'''

In [ ]:
import tensorflow as tf

In [ ]:
t = tf.keras.preprocessing.text.Tokenizer()

In [ ]:
t.fit_on_texts([text])

In [ ]:
vocab_size = len(t.word_index) + 1
print(vocab_size)

50


In [ ]:
t.word_index

In [ ]:
# 1. 
id_to_word = dict([ (value, key) for key,value in t.word_index.items()])
# 2. 
id_to_word = {}
for key,value in t.word_index.items():
  id_to_word[value] = key

In [ ]:
for line in text.split('\n'):
  print(line)


동해 물과 백두산이 마르고 닳도록
하느님이 보우하사 우리나라 만세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
남산 위에 저 소나무, 철갑을 두른 듯
바람 서리 불변함은 우리 기상일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
가을 하늘 공활한데 높고 구름 없이
밝은 달은 우리 가슴 일편단심일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
이 기상과 이 맘으로 충성을 다하여
괴로우나 즐거우나 나라 사랑하세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.



In [ ]:
sequences = list()
for line in text.split('\n'):
  encoded = t.texts_to_sequences([line])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)

In [ ]:
maxlen = 0 
for seq in sequences:
  if len(seq) > maxlen :
    maxlen = len(seq)

In [ ]:
sequences = tf.keras.preprocessing.sequence.pad_sequences(sequences, value=0, maxlen=maxlen)

In [ ]:
sequences[:3]

array([[ 0,  0,  0,  0,  0, 12, 13],
       [ 0,  0,  0,  0, 12, 13, 14],
       [ 0,  0,  0, 12, 13, 14, 15]], dtype=int32)

In [ ]:
X = sequences[:,:-1]
y = sequences[:,-1]

In [ ]:
X.shape, y.shape

((62, 6), (62,))

In [ ]:
y[:5]

array([13, 14, 15, 16, 18], dtype=int32)

In [ ]:
X[:5]

array([[ 0,  0,  0,  0,  0, 12],
       [ 0,  0,  0,  0, 12, 13],
       [ 0,  0,  0, 12, 13, 14],
       [ 0,  0, 12, 13, 14, 15],
       [ 0,  0,  0,  0,  0, 17]], dtype=int32)

In [ ]:
y = tf.keras.utils.to_categorical(y, num_classes=vocab_size)

In [ ]:
y[:3]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]], dtype=float32)

## 모델 정의

In [ ]:
# input -> embedding
# LSTM -> 
# Dense -> softmax

In [ ]:
model = tf.keras.models.Sequential(
    [
     tf.keras.layers.Embedding(vocab_size, 10),
     tf.keras.layers.LSTM(128),
     tf.keras.layers.Dense(vocab_size, activation='softmax'),
    ]
)

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X,y, epochs=200)

Epoch 1/200
2/2 [==============================] - 0s 5ms/step - loss: 0.4347 - accuracy: 0.9677
Epoch 2/200
2/2 [==============================] - 0s 5ms/step - loss: 0.4289 - accuracy: 0.9516
Epoch 3/200
2/2 [==============================] - 0s 4ms/step - loss: 0.4246 - accuracy: 0.9516
Epoch 4/200
2/2 [==============================] - 0s 4ms/step - loss: 0.4198 - accuracy: 0.9516
Epoch 5/200
2/2 [==============================] - 0s 4ms/step - loss: 0.4202 - accuracy: 0.9677
Epoch 6/200
2/2 [==============================] - 0s 4ms/step - loss: 0.4098 - accuracy: 0.9839
Epoch 7/200
2/2 [==============================] - 0s 6ms/step - loss: 0.4054 - accuracy: 0.9839
Epoch 8/200
2/2 [==============================] - 0s 8ms/step - loss: 0.4020 - accuracy: 1.0000
Epoch 9/200
2/2 [==============================] - 0s 6ms/step - loss: 0.3927 - accuracy: 0.9677
Epoch 10/200
2/2 [==============================] - 0s 5ms/step - loss: 0.3961 - accuracy: 0.9677
Epoch 11/200
2/2 [===========

* 학습된 모델
* 현재 인풋 (단어 하나 or 시작점 표시)
* 생성하려는 문장의 길이 
* 결과를 단어로 변환해주기 위한 TOKENIZER

In [ ]:
X[:2]

array([[ 0,  0,  0,  0,  0, 12],
       [ 0,  0,  0,  0, 12, 13]], dtype=int32)

In [ ]:
import numpy as np

In [ ]:
np.argmax(model.predict(X[:2]), axis=1)

array([13, 14])

In [ ]:
# '대한' 다음 단어를 생성하려하면
# '대한' => input 모양에 맞게 변형
encoded = t.texts_to_sequences(['대한'])
encoded = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=maxlen)

In [ ]:
result = model.predict(encoded)

In [ ]:
np.argmax(result, axis=1)

array([6])

In [ ]:
id_to_word[np.argmax(result, axis=1)[0]]

'사람'

In [ ]:
maxlen

7

In [ ]:
t.texts_to_sequences([current_input])

[[5, 6, 7, 8, 9, 9]]

In [ ]:
n = 10
current_input = '대한'

result_str = current_input
for i in range(n):
  # print(current_input)
  encoded = t.texts_to_sequences([current_input])
  print(encoded)
  encoded = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=maxlen-1)
  print(encoded)

  result = model.predict(encoded)
  result_word = id_to_word[np.argmax(result, axis=1)[0]]
  result_str += ' ' + result_word
  current_input += ' ' + result_word


[[5]]
[[0 0 0 0 0 5]]
[[5, 6]]
[[0 0 0 0 5 6]]
[[5, 6, 7]]
[[0 0 0 5 6 7]]
[[5, 6, 7, 8]]
[[0 0 5 6 7 8]]
[[5, 6, 7, 8, 9]]
[[0 5 6 7 8 9]]
[[5, 6, 7, 8, 9, 9]]
[[5 6 7 8 9 9]]
[[5, 6, 7, 8, 9, 9, 10]]
[[ 6  7  8  9  9 10]]
[[5, 6, 7, 8, 9, 9, 10, 41]]
[[ 7  8  9  9 10 41]]
[[5, 6, 7, 8, 9, 9, 10, 41, 27]]
[[ 8  9  9 10 41 27]]
[[5, 6, 7, 8, 9, 9, 10, 41, 27, 26]]
[[ 9  9 10 41 27 26]]


In [ ]:
result_str

'대한 사람 대한으로 길이 보전하세 보전하세 우리 일편단심일세 듯 두른 두른'

In [ ]:
def sentence_generation(model, t, current_input, n):
  result_str = current_input
  for i in range(n):
    encoded = t.texts_to_sequences([current_input])
    encoded = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=maxlen-1)

    result = model.predict(encoded)
    result_word = id_to_word[np.argmax(result, axis=1)[0]]
    result_str += ' ' + result_word
    current_input += ' ' + result_word

  return result_str

In [ ]:
print(sentence_generation(model, t, '마르고',n=9))

마르고 삼천리 화려 강산 길이 길이 보전하세 보전하세 우리 일편단심일세
