1. 퍼셉트론
2. 활성화 함수 -> step function, sigmoid, softmax, 항등함수
3. 행렬 곱

3층 신경망 구현하기
1. input 정하기
2. 가중치 정의, 편향 정의(w, b)
3. 계산(input * w + b) -> 활성화 함수
4. 마지막 output 계산을 위한 활성화 함수

In [1]:
def step_function(x):
  if x > 0 :
    return 1
  else:
    return 0

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [7]:
def identity_function(x):
  return x

In [10]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [11]:
import numpy as np

# input 정의
x = np.array([1.0, 0.5])

# 가중치 정의, 편향 정의
network = {}
network['W1'] = np.array([
                          [0.1, 0.3, 0.5], 
                          [0.2, 0.4, 0.6]
                          ])

network['b1'] = np.array([0.1, 0.2, 0.3])

network['W2'] = np.array([[0.1, 0.4], 
                          [0.2, 0.5], 
                          [0.3, 0.6]])

network['b2'] = np.array([0.1, 0.2])

network['W3'] = np.array([[0.1, 0.3],
                          [0.2, 0.4]])

network['b3'] = np.array([0.1, 0.2])

W1, W2, W3 = network['W1'], network['W2'], network['W3']
b1, b2, b3 = network['b1'], network['b2'], network['b3']


#input -> 1층
a1 = np.dot(x, W1) + b1
z1 = sigmoid(a1)

# 1층 -> 2층
a2 = np.dot(z1, W2) + b2
z2 = sigmoid(a2)

# 2층 -> 3층
a3 = np.dot(z2, W3) + b3

# 3층 -> 마지막 활성함수 통과
# 항등함수 or softmax 함수

y_identity = identity_function(a3)
y_softmax = softmax(a3)





In [12]:
k = np.array([1, 2, 3])

In [13]:
k2 = k / 5

In [14]:
k2

array([0.2, 0.4, 0.6])

In [15]:
ke = np.exp(k)

In [16]:
ke

array([ 2.71828183,  7.3890561 , 20.08553692])

In [17]:
k_sum = np.sum(ke)

In [18]:
k_sum

30.19287485057736

In [19]:
ke / k_sum

array([0.09003057, 0.24472847, 0.66524096])

In [20]:
np.sum(ke/k_sum)

1.0